version: "2"

services:
  notaryserver:
    image: mbentley/notary-server:0.3.0
    restart: unless-stopped
    depends_on:
      - notarymysql
      - notarysigner
    networks:
      dtr-ol:
        aliases:
          - server
    command: -config=/notary/server/server-config.json

  notarysigner:
    image: mbentley/notary-signer:0.3.0
    restart: unless-stopped
    environment:
      - NOTARY_SIGNER_DEFAULT_ALIAS=timestamp_1
      - NOTARY_SIGNER_TIMESTAMP_1=testpassword
    depends_on:
      - notarymysql
    networks:
      dtr-ol:
        aliases:
          - signer
    command: -config=/notary/server/signer-config.json

  notarymysql:
    image: mbentley/notary-mariadb:0.3.0
    restart: unless-stopped
    volumes:
      - notary_data:/var/lib/mysql
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    networks:
      dtr-ol:
        aliases:
          - mysql
    command: mysqld --innodb_file_per_table

volumes:
  notary_data:
    driver: local

networks:
  dtr-ol:
    external:
      name: dtr-ol
