version: "2"

services:
  notaryserver:
    image: mbentley/notary-server:0.2.0
    restart: unless-stopped
    links:
      - notarymysql
      - notarysigner
    networks:
      - dtr
    command: -config=/notary/server/server-config.json

  notarysigner:
    image: mbentley/notary-signer:0.2.0
    restart: unless-stopped
    environment:
      - ENV NOTARY_SIGNER_DEFAULT_ALIAS=timestamp_1
      - ENV NOTARY_SIGNER_TIMESTAMP_1=testpassword
    links:
      - notarymysql
    networks:
      - dtr
    command: -config=/notary/server/signer-config.json

  notarymysql:
    image: mbentley/notary-mariadb:0.2.0
    restart: unless-stopped
    volumes:
      - notary_data:/var/lib/mysql
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    networks:
      - dtr
    command: mysqld --innodb_file_per_table

volumes:
  notary_data:
    driver: local

networks:
  dtr:
    external:
      name: dtr
