version: "2"

services:
  migrate-server:
    image: mbentley/notary-migrate:0.3.0
    depends_on:
      - mysql
    environment:
      - SERVICE_NAME=notary_server
    networks:
      - notary

  migrate-signer:
    image: mbentley/notary-migrate:0.3.0
    depends_on:
      - mysql
    environment:
      - SERVICE_NAME=notary_signer
    networks:
      - notary

  mysql:
    image: mbentley/notary-mariadb:0.3.0
    volumes:
      - notary_data:/var/lib/mysql
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    networks:
      - notary
    command: mysqld --innodb_file_per_table

volumes:
  notary_data:
    driver: local

networks:
  notary:
    driver: bridge
